name: AMI-Build-ci

on:
  pull_request:
    branches: ["main"]
    
jobs:
  validate:
    name: Validate webapp

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 'Thenothing1!'
          MYSQL_DATABASE: 'cloud'

        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x

    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: cloud
      DB_USERNAME: root
      DB_PASSWORD: Thenothing1!
      FILE_PATH: ./opt/users.csv
    

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }} 
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Installing nodemon
      run: npm install nodemon
    
    - name: Run Jest Tests
      run: npm test

    

  build:
    name: Build Ami
    runs-on: ubuntu-latest
    needs: validate 

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: Setup Packer
          uses: hashicorp/setup-packer@main
          id: setup
          with:
              version: "latest"

        - name: Packer init
          run: |
                packer init packer/aws-debian.pkr.hcl
                  
        - name: Format Check Pakcer File
          run: |
                if ! packer fmt -check packer/aws-debian.pkr.hcl; then
                    echo "Packer file formatting check failed. Exiting the pipeline."
                    exit 1
                  fi
                  
        - name: Validate Packer File
          run: |
                if ! packer validate packer/aws-debian.pkr.hcl; then
                  echo "Packer validation check failed. Exiting the pipeline."
                  exit 1
                fi

        - name: Publish Web App Artifact
          uses: actions/upload-artifact@v2
          with:
                name: web-app
                path: dist
                      
        - name: Build AMI
          run: |
                export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
                export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
                packer build packer/aws-debian.pkr.hcl



     




    
